function d(a,b){this.width=a;this.height=b}function e(a){this.id=a}e.prototype.element=function(){return this.id?document.getElementById(this.id):null};function f(a){if(a=a.element())switch(a.tagName){case "INPUT":switch(a.type){case "checkbox":return 1;case "radio":return 2;case "text":var b=a.classList;return a.color||b.contains("color")?3:0}break;case "SELECT":return 4}return null}e.prototype.get=function(){switch(f(this)){case 1:case 2:return Boolean(this.element().checked);case 0:case 4:case 3:return this.element().value}};
e.prototype.set=function(a){switch(f(this)){case 1:case 2:this.element().checked=Boolean(a);break;case 0:case 4:this.element().value=a;break;case 3:this.element().color.fromString(a)}};function g(a){return[].map.call((a||document).querySelectorAll("input,textarea,select"),function(a){return new e(a.id)}).filter(function(a){return null!=f(a)})}function h(a){var b={};a.forEach(function(a){null!=f(a)&&(this[a.id]=a.get())},b);return b}
function k(a,b){a.forEach(function(a){null!=f(a)&&b.hasOwnProperty(a.id)&&a.set(b[a.id])})}function m(a,b){return function(){return b.apply(a,arguments)}}function n(){this.data={}}n.prototype.getItem=function(a){return window.localStorage?window.localStorage.getItem(a):this.data[a]};n.prototype.setItem=function(a,b){window.localStorage?window.localStorage.setItem(a,b):this.data[a]=b};n.prototype.clear=function(){window.localStorage?window.localStorage.clear():this.data={}};var p=new n;
function q(a,b){this.m=a;this.s=b;this.d=g(this.element());this.d.forEach(function(a){null!=f(a)&&(a.element().onchange=m(this,this.c))},this);this.c()}q.prototype.c=function(){this.data=h(this.d);this.o&&this.o()};q.prototype.element=function(){return document.getElementById(this.s)};q.prototype.save=function(){var a=this.m;a&&p.setItem(a,JSON.stringify(this.data));console.log("Settings saved.")};
q.prototype.load=function(){var a;a:{if(a=this.m)if(a=p.getItem(a),null!=a){a=JSON.parse(a);break a}a=null}return a?(console.log("Settings loaded."),k(this.d,a),this.c(),!0):!1};var r=null,v=null;function w(a){r=a;v&&v()}function x(a){w({gameInfo:a,resolutionChanged:!0,focusChanged:!0,runningChanged:!0,gameChanged:!0})}function y(){var a=z;Boolean(window.overwolf)&&overwolf.windows.obtainDeclaredWindow("MainWindow",function(b){"success"===b.status?(b=b.window.id,(new RegExp("_MainWindow".replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")+"$")).test(b)&&(b=b.slice(0,-11)),a("MainWindow",b)):a("MainWindow",null)})}Boolean(window.overwolf)&&overwolf.games.onGameInfoUpdated.addListener(w);function A(a,b){switch(b){case 0:this.outline=a.circle();this.shape=a.circle();break;case 1:this.outline=a.rect();this.shape=a.rect();break;default:throw"Invalid shape specified to nx.svg.Shape constructor.";}this.type=b;this.p=0;this.outlineColor="#FF00FF"}function B(a,b,c){a=a.shape.attr(b);if(null==a)"undefined"==typeof c||(a=c);else if(/px$/.test(a)){if(c=parseFloat(a),a==c+"px")return c}else!isNaN(a)&&(a=parseFloat(a));return a}function C(a,b){b.add(a.outline,a.shape)}
function D(a){var b=0;"none"!=B(a,"stroke","none")&&(b=B(a,"strokeWidth",0));!(1!=a.type||B(a,"width",0)&&B(a,"height",0))||0==a.type&&!B(a,"r",0)?a.outline.attr({stroke:"none"}):(a.outline.attr({stroke:a.outlineColor}),a.outline.attr({strokeWidth:b+2*a.p}))}A.prototype.attr=function(a){if("string"==typeof a)return this.shape.attr(a);this.shape.attr(a);this.outline.attr(a);D(this);return this};function E(a,b,c){a.outlineColor=b;a.p=parseFloat(c);D(a)};var G;function H(a){this.n=a;this.a=Snap(this.element());this.b=this.a.group();this.cross=this.a.group();this.l=new A(this.a,0);C(this.l,this.b);this.f=new A(this.a,0);C(this.f,this.b);C(this.f,this.b);this.e=new A(this.a,1);C(this.e,this.b);C(this.e,this.b);this.b.add(this.cross);this.k=new A(this.a,1);C(this.k,this.cross);this.h=new A(this.a,1);C(this.h,this.cross);this.i=new A(this.a,1);C(this.i,this.cross);this.j=new A(this.a,1);C(this.j,this.cross);this.g=0}
H.prototype.element=function(){var a=document.getElementById(this.n);if(!a)throw"Could not find a SVG DOM Element with id of "+this.n;return a};function I(a){return a?"visible":"hidden"}function J(a,b){b%=360;a.cross.stop().attr({transform:"r"+b+",0,0"})}H.prototype.q=function(){J(this,0);this.cross.animate({transform:"r360,0,0"},this.g,m(this,this.q))};var K=null,L=null;
function M(){console.log("Rendering reticle.");var a=K,b=L.data,c;c=a.a.node.parentNode;c=new d(c.offsetWidth,c.offsetHeight);a.element().setAttribute("shape-rendering",b.shapeRendering);a.b.attr({opacity:b.opacity,transform:"t"+[c.width/2,c.height/2]});a.l.attr({r:b.circleDiameter/2,fill:"none",stroke:b.circleColor,visibility:I(b.circleEnabled),strokeWidth:b.circleThickness});E(a.l,b.circleStrokeColor,b.circleStrokeSize);c=b.centerDiameter/2;a.f.attr({r:c,fill:b.centerColor,visibility:I(b.centerEnabled&&
"circle"==b.centerShape)});E(a.f,b.centerStrokeColor,b.centerStrokeSize);a.e.attr({width:b.centerDiameter,height:b.centerDiameter,fill:b.centerColor,visibility:I(b.centerEnabled&&"square"==b.centerShape),transform:"t"+[-c,-c]});E(a.e,b.centerStrokeColor,b.centerStrokeSize);c=-b.crossLength-b.crossSpread;var t=-(b.crossThickness/2),u={fill:b.crossColor,visibility:I(b.crossEnabled)},F={width:b.crossThickness,height:b.crossLength},l={width:b.crossLength,height:b.crossThickness};a.k.attr(u).attr(F).attr({transform:"t"+
[t,c]});a.h.attr(u).attr(F).attr({transform:"t"+[t,b.crossSpread]});a.i.attr(u).attr(l).attr({transform:"t"+[c,t]});a.j.attr(u).attr(l).attr({transform:"t"+[b.crossSpread,t]});E(a.k,b.crossStrokeColor,b.crossStrokeSize);E(a.h,b.crossStrokeColor,b.crossStrokeSize);E(a.i,b.crossStrokeColor,b.crossStrokeSize);E(a.j,b.crossStrokeColor,b.crossStrokeSize);c=parseInt(b.crossSpinPeriod,10);c!=a.g&&(0<c?(a.g=c,a.q()):(a.g=0,J(a,b.crossRotation)))}function N(){console.log("Data changed.");M()}
function O(){console.log("Window resized.");M()}function P(){var a,b;r&&r.gameInfo?(a=(r&&r.gameInfo).width,b=(r&&r.gameInfo).height):(a=window.screen.width,b=window.screen.height);var c=G;Boolean(window.overwolf)&&(overwolf.windows.changePosition(c,0,0),overwolf.windows.changeSize(c,a,b))}function z(a,b){"MainWindow"!=a||G||(G=b,v=P,Boolean(window.overwolf)&&overwolf.games.getRunningGameInfo(x))}
window.main={init:function(a,b,c){Boolean(window.overwolf)||(document.body.bgColor="black");K=new H(a);L=new q(b,c);L.d.forEach(function(a){if(3==f(a)){var b=a.element();b.color||(b.color=new jscolor.color(b));var b=b.color,c={hash:!0,pickerClosable:!0,onImmediateChange:m(L,L.c)},l;for(l in c)c.hasOwnProperty(l)&&(b[l]=c[l]);a.set(a.get())}});L.c();window.addEventListener("resize",O);L.load();L.o=N;Boolean(window.overwolf)?(overwolf.settings.registerHotKey("reticle_menu",function(a){"success"==a.status&&
(console.log("Reticle menu hotkey triggered."),L.element().style.display="block")}),y()):L.element().style.display="block";M()},onDataChanged:N};
