function d(a,b){this.width=a;this.height=b}function e(a){this.id=a}e.prototype.element=function(){return this.id?document.getElementById(this.id):null};function f(a){if(a=a.element())switch(a.tagName){case "INPUT":switch(a.type){case "checkbox":return 1;case "radio":return 2;case "text":var b=a.classList;return a.color||b.contains("color")?3:0}break;case "SELECT":return 4}return null}e.prototype.get=function(){switch(f(this)){case 1:case 2:return Boolean(this.element().checked);case 0:case 4:case 3:return this.element().value}};
e.prototype.set=function(a){switch(f(this)){case 1:case 2:this.element().checked=Boolean(a);break;case 0:case 4:this.element().value=a;break;case 3:this.element().color.fromString(a)}};function g(a){return[].map.call((a||document).querySelectorAll("input,textarea,select"),function(a){return new e(a.id)}).filter(function(a){return null!=f(a)})}function h(a){var b={};a.forEach(function(a){null!=f(a)&&(this[a.id]=a.get())},b);return b}
function k(a,b){a.forEach(function(a){null!=f(a)&&b.hasOwnProperty(a.id)&&a.set(b[a.id])})}function l(a,b){return function(){return b.apply(a,arguments)}}function n(){this.data={}}n.prototype.getItem=function(a){return window.localStorage?window.localStorage.getItem(a):this.data[a]};n.prototype.setItem=function(a,b){window.localStorage?window.localStorage.setItem(a,b):this.data[a]=b};n.prototype.clear=function(){window.localStorage?window.localStorage.clear():this.data={}};var p=new n;
function q(a,b){this.o=a;this.A=b;this.e=g(this.element());this.e.forEach(function(a){null!=f(a)&&(a.element().onchange=l(this,this.d))},this);this.d()}q.prototype.d=function(){this.data=h(this.e);this.t&&this.t()};q.prototype.element=function(){return document.getElementById(this.A)};function r(a){t.element().style.display=a?"block":"none"}q.prototype.save=function(){var a=this.o;a&&p.setItem(a,JSON.stringify(this.data));console.log("Settings saved.")};
q.prototype.load=function(){var a;a:{if(a=this.o)if(a=p.getItem(a),null!=a){a=JSON.parse(a);break a}a=null}return a?(console.log("Settings loaded."),k(this.e,a),this.d(),!0):!1};function u(){return Boolean(window.overwolf)}var v=null,y=null;function z(a){v=a;y&&y()}function A(a){z({gameInfo:a,resolutionChanged:!0,focusChanged:!0,runningChanged:!0,gameChanged:!0})}function B(){var a=C;u()&&overwolf.windows.obtainDeclaredWindow("MainWindow",function(b){"success"===b.status?(b=b.window.id,(new RegExp("_MainWindow".replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")+"$")).test(b)&&(b=b.slice(0,-11)),a("MainWindow",b)):a("MainWindow",null)})}u()&&overwolf.games.onGameInfoUpdated.addListener(z);function D(a,b){switch(b){case 0:this.outline=a.circle();this.shape=a.circle();break;case 1:this.outline=a.rect();this.shape=a.rect();break;default:throw"Invalid shape specified to nx.svg.Shape constructor.";}this.type=b;this.u=0;this.outlineColor="#FF00FF"}function E(a,b,c){a=a.shape.attr(b);if(null==a)"undefined"==typeof c||(a=c);else if(/px$/.test(a)){if(c=parseFloat(a),a==c+"px")return c}else!isNaN(a)&&(a=parseFloat(a));return a}function F(a,b){b.add(a.outline,a.shape)}
function G(a){var b=0;"none"!=E(a,"stroke","none")&&(b=E(a,"strokeWidth",0));!(1!=a.type||E(a,"width",0)&&E(a,"height",0))||0==a.type&&!E(a,"r",0)?a.outline.attr({stroke:"none"}):(a.outline.attr({stroke:a.outlineColor}),a.outline.attr({strokeWidth:b+2*a.u}))}D.prototype.attr=function(a){if("string"==typeof a)return this.shape.attr(a);this.shape.attr(a);this.outline.attr(a);G(this);return this};function I(a,b,c){a.outlineColor=b;a.u=parseFloat(c);G(a)};var J;
function K(a){this.q=a;this.a=Snap(this.element());this.c=this.a.group();this.cross=this.a.group();this.n=new D(this.a,0);F(this.n,this.c);this.g=new D(this.a,0);F(this.g,this.c);F(this.g,this.c);this.f=new D(this.a,1);F(this.f,this.c);F(this.f,this.c);this.c.add(this.cross);this.m=new D(this.a,1);F(this.m,this.cross);this.j=new D(this.a,1);F(this.j,this.cross);this.k=new D(this.a,1);F(this.k,this.cross);this.l=new D(this.a,1);F(this.l,this.cross);this.image=this.a.image();this.c.add(this.image);this.b=
new Image;this.b.onload=l(this,this.w);this.b.onerror=l(this,this.p);this.h=0;this.s=1;this.i=""}K.prototype.w=function(){console.log("Loaded: "+[this.b.width,this.b.height]);var a=this.b.width,b=this.b.height;this.image.attr({width:a,height:b,"xlink:href":this.i,transform:"t"+[-a/2,-b/2]+" s"+this.s})};K.prototype.p=function(){this.b.removeAttribute("src");this.image.attr({width:0,height:0});this.image.node.removeAttribute("href")};
K.prototype.element=function(){var a=document.getElementById(this.q);if(!a)throw"Could not find a SVG DOM Element with id of "+this.q;return a};function L(a){return a?"visible":"hidden"}function M(a,b){b%=360;a.cross.stop().attr({transform:"r"+b+",0,0"})}K.prototype.v=function(){M(this,0);this.cross.animate({transform:"r360,0,0"},this.h,l(this,this.v))};var N=null,t=null;
function O(){console.log("Rendering reticle.");var a=N,b=t.data,c;c=a.a.node.parentNode;c=new d(c.offsetWidth,c.offsetHeight);a.element().setAttribute("shape-rendering",b.shapeRendering);a.c.attr({opacity:b.opacity,transform:"t"+[c.width/2,c.height/2]});a.n.attr({r:b.circleDiameter/2,fill:"none",stroke:b.circleColor,visibility:L(b.circleEnabled),strokeWidth:b.circleThickness});I(a.n,b.circleStrokeColor,b.circleStrokeSize);c=b.centerDiameter/2;a.g.attr({r:c,fill:b.centerColor,visibility:L(b.centerEnabled&&
"circle"==b.centerShape)});I(a.g,b.centerStrokeColor,b.centerStrokeSize);a.f.attr({width:b.centerDiameter,height:b.centerDiameter,fill:b.centerColor,visibility:L(b.centerEnabled&&"square"==b.centerShape),transform:"t"+[-c,-c]});I(a.f,b.centerStrokeColor,b.centerStrokeSize);c=-b.crossLength-b.crossSpread;var w=-(b.crossThickness/2),x={fill:b.crossColor,visibility:L(b.crossEnabled)},H={width:b.crossThickness,height:b.crossLength},m={width:b.crossLength,height:b.crossThickness};a.m.attr(x).attr(H).attr({transform:"t"+
[w,c]});a.j.attr(x).attr(H).attr({transform:"t"+[w,b.crossSpread]});a.k.attr(x).attr(m).attr({transform:"t"+[c,w]});a.l.attr(x).attr(m).attr({transform:"t"+[b.crossSpread,w]});I(a.m,b.crossStrokeColor,b.crossStrokeSize);I(a.j,b.crossStrokeColor,b.crossStrokeSize);I(a.k,b.crossStrokeColor,b.crossStrokeSize);I(a.l,b.crossStrokeColor,b.crossStrokeSize);c=parseInt(b.crossSpinPeriod,10);c!=a.h&&(0<c?(a.h=c,a.v()):(a.h=0,M(a,b.crossRotation)));a.s=b.imageScale;a.i=b.imageURL;a.b.src!=a.i&&a.p();a.image.attr({visibility:L(b.imageEnabled)});
a.b.src=a.i;a.w()}function P(){console.log("Data changed.");O()}function Q(){console.log("Window resized.");O()}function R(){var a,b;v&&v.gameInfo?(a=(v&&v.gameInfo).width,b=(v&&v.gameInfo).height):(a=window.screen.width,b=window.screen.height);var c=J;u()&&(overwolf.windows.changePosition(c,0,0),overwolf.windows.changeSize(c,a,b))}function C(a,b){"MainWindow"!=a||J||(J=b,y=R,u()&&overwolf.games.getRunningGameInfo(A))}
window.main={init:function(a,b,c){u()||(document.body.bgColor="black");N=new K(a);t=new q(b,c);t.e.forEach(function(a){if(3==f(a)){var b=a.element();b.color||(b.color=new jscolor.color(b));var b=b.color,c={hash:!0,pickerClosable:!0,onImmediateChange:l(t,t.d)},m;for(m in c)c.hasOwnProperty(m)&&(b[m]=c[m]);a.set(a.get())}});t.d();window.addEventListener("resize",Q);t.load();t.t=P;u()?(overwolf.settings.registerHotKey("reticle_menu",function(a){"success"==a.status&&(console.log("Reticle menu hotkey triggered."),
r(!0))}),B()):r(!0);O()},onDataChanged:P,save:function(){t.save()},load:function(){t.load()},hide:function(){u()&&r(!1)}};
